remote_theme: "manid2/lone-wolf-theme"
url: https://taniyacato.github.io/
baseurl: /jk-test/
title: Sketched By Taniya
description: This is my site 
instagram: "https://www.instagram.com/taniyyaaa/?hl=en"
author: Taniya Lynee Trinidad
